import ras from '../assets/images/ras.webp';
import joke from '../assets/images/joke.webp';
import lofi from '../assets/images/lofi.webp';
import blog from '../assets/images/blog.webp';
import docAid from '../assets/images/docAid.webp';
import LifeInsureEase from '../assets/images/lifeinsureease.webp';
import Portfolio from '../assets/images/portfolio.webp';
import BaufestSystem from '../assets/images/baufest.png';
import EZSystem from '../assets/images/ez.png';
import ICBCSystem from '../assets/images/icbc.png';
import McrSystem from '../assets/images/mcr.jpg';
import CarrerLabSystem from '../assets/images/carrerlab.png';
import RutaSystem from '../assets/images/ruta.jpg';
import ConfiteriaSystem from '../assets/images/confiteria.png';
import MostelaSystem from '../assets/images/mostela.png';
import BarcelonaSystem from '../assets/images/barcelona.png';
import FinvivirSystem from '../assets/images/finvivir.png';
import FinvivirAdminSystem from '../assets/images/finviviradmin.png';
import StartFunSystem from '../assets/images/startfun.png';
import HotelesYucatanSystem from '../assets/images/hotelesyucatan.png';
import HotelesMexicanosSystem from '../assets/images/hotelesmexicanos.png';
import StreamingSystem from '../assets/images/streaming.png';
import ChocolateSystem from '../assets/images/chocolate.png';
import KaviaSystem from '../assets/images/kavia.png';
import HaciendaSystem from '../assets/images/hacienda.png';
import BikerTourSystem from '../assets/images/bikertours.png';
import RadarLibrary from '../assets/images/radar.png';
import Freelance from '../assets/images/freelance.png';
import CartManagementSystem from '../assets/images/cart-management-system.webp';
const data = [
  {
    name: 'MCR Construction Machinery',
    type: 'Desktop & Mobile',
    url: '',
    github: '',
    image: McrSystem,
    slug: 'mcr-construction-machiney',
    description:
      'This is a suite application when administrator register reports per week with hour and cost from operators. The System made using Flutter and Google Material with the help of Supabase. There is a one project with difference build, one for Desktop and anoter for Mobile.',
    tech: [
      'Flutter',
      'Supabase',
      'Google Material',
      'GitHub',
      'Private Project',
      'Clean Architecture',
    ],
  },
  {
    name: 'Radar render',
    type: 'Library',
    url: 'https://punteriacero.github.io/torta/',
    github: 'https://github.com/PunteriaCero/torta/tree/main',
    image: RadarLibrary,
    slug: 'radar-render',
    description:
      'This is a component initiative to render radar component and target. The Library made using ReactJS.',
    tech: [
      'ReactJS',
      'D3js',
      'Babel',
      'Webpack',
      'Rollup',
      'MUI UI tools',
      'StyledComponents',
      'emotion CSS',
      'HTML',
      'GIT',
      'GitHub Actions',
      'CI/CD GitHub',
    ],
  },
  {
    name: 'Barcelona Estudio',
    type: 'Website',
    url: 'https://www.tamaramartinez.com/es/inicio/',
    github: '',
    image: BarcelonaSystem,
    slug: 'barcelona-estudio',
    description:
      'This is a architect website made using Wordpress with page builder.',
    tech: [
      'Wordpress',
      'HTML',
      'Javascript',
      'Css',
      'Figma',
      'Javascript',
      'PHP',
      'MySQL',
      'ACF',
      'Custom Shortcode',
      'WPBakery Page Builder',
    ],
  },
  {
    name: 'BitCerts',
    type: 'WebApp',
    url: '',
    github: '',
    image: BaufestSystem,
    slug: 'bitcerts',
    description:
      'This is a application when people of Baufest could be generate a certification via blockchain. The System made using ReactJS.',
    tech: [
      'ReactJS',
      'Redux',
      'Jest',
      'React Testing Library',
      'Formik',
      'MUI UI tools',
      'StyledComponents',
      'emotion CSS',
      'HTML',
      'GIT',
      'GitLab',
      'CI/CD GitLab',
      'Husky',
    ],
  },
  {
    name: 'LendingGo',
    type: 'WebApp',
    url: '',
    github: '',
    image: BaufestSystem,
    slug: 'lending-go',
    description:
      'This is a application when you can request a credit bank. The System made using ReactJS and NextJS',
    tech: [
      'ReactJS',
      'NextJS',
      'Redux',
      'Jest',
      'React Testing Library',
      'Formik',
      'MUI UI tools',
      'StyledComponents',
      'emotion CSS',
      'HTML',
      'GIT',
      'AWS Repository',
      'Husky',
    ],
  },
  {
    name: 'Challenge',
    type: 'WebApp',
    url: '',
    github: '',
    image: BaufestSystem,
    slug: 'challenge',
    description:
      'This is a challenge application that baufest sent me for a opportunity to work with them. The System made using Angular',
    tech: [
      'Angular',
      'Angular Boostrap',
      'Karma/Jasmine',
      'CSS',
      'Sass',
      'HTML',
      'GIT',
      'GitLab',
    ],
  },
  {
    name: 'ICBC',
    type: 'WebApp',
    url: '',
    github: '',
    image: ICBCSystem,
    slug: 'icbc',
    description:
      'This are many applications when customer was able to request a credit bank. The System made using Angular',
    tech: [
      'Angular',
      'Karma/Jasmine',
      'Postman',
      'Miro',
      'PrimeNG',
      'NGXS',
      'HTML',
      'GIT',
      'GitLab',
      'SonarQube',
      'Husky',
    ],
  },
  {
    name: 'Booking Engine',
    type: 'WebApp',
    url: '',
    github: '',
    image: HotelesMexicanosSystem,
    slug: 'booking-engine',
    description:
      'This is a booking application when customer is able to see a list of rooms availables and is able to reserve. The System made using Laravel and VueJS. Api was provided by the backend team.',
    tech: [
      'HTML',
      'Javascript',
      'VueJS',
      'Vue Bootstrap',
      'Webpack',
      'NPM',
      'Css',
      'Sass',
      'Mobilscroll',
      'PHP',
      'Laravel',
      'MariaDB',
      'Paypal',
      'Stripe',
      'Paypal',
      'OpenPay',
      'Postman',
      'API Rest',
      'Trello',
      'Git',
    ],
  },
  {
    name: 'Backoffice Hotel',
    type: 'WebApp',
    url: '',
    github: '',
    image: EZSystem,
    slug: 'backoffice-hotel',
    description:
      'This is a backoffice application when the administrator is able to manage all operation of own hotel. The System made using Angular and Laravel for API.',
    tech: [
      'HTML',
      'Javascript',
      'Angular',
      'Jasmine/Karma',
      'Bootstrap',
      'Css',
      'Sass',
      'ngx-permission',
      'PHP',
      'Laravel',
      'MySQL',
      'Postman',
      'API Rest',
      'Trello',
      'Git',
      'Azure repository',
    ],
  },
  {
    name: 'Channel Manager',
    type: 'SDK',
    url: '',
    github: '',
    image: EZSystem,
    slug: 'channerl-manager',
    description:
      'This is a channerl manager application when easy-rez connected with others channel around at the world and downloaded all the reservation in local system. The System made using PHP.',
    tech: [
      'PHP',
      'PHPUnit',
      'MySQL',
      'Postman',
      'API Rest',
      'Trello',
      'Git',
      'Azure repository',
    ],
  },
  {
    name: 'Mexico billing system',
    type: 'WebApp',
    url: '',
    github: '',
    image: EZSystem,
    slug: 'billing-system',
    description:
      'This is a billing application when the administrator is able to generate invoices and generate and reports in PDF and Excel. The System made using AngularJS and Laravel.',
    tech: [
      'HTML',
      'Javascript',
      'Angular',
      'Bootstrap',
      'Css',
      'Sass',
      'PHP',
      'Laravel',
      'MySQL',
      'Postman',
      'API Rest',
      'SOAP & REST Client',
      'XML',
      'Trello',
      'MVC pattern desing',
      'dompdf',
      'Git',
      'Bitbucket',
    ],
  },
  {
    name: 'Mobile Booking Engine',
    type: 'MobileHybrid',
    url: 'https://play.google.com/store/apps/details?id=com.easyrez.hotelesyucatan&hl=es_MX&gl=US',
    github: '',
    image: HotelesYucatanSystem,
    slug: 'mobile-booking-engine',
    description:
      'This is a booking mobile application when the customer is able to search and compare cost of rooms availables before to reserve. The System made using Ionic and Angular.',
    tech: [
      'HTML',
      'Angular',
      'Sass',
      'XCODE',
      'Android Studio',
      'Google Play Console',
      'Maps SDK Google',
      'Geolocation',
      'App Store',
      'Postman',
      'Mobilscroll',
      'Trello',
      'Git',
    ],
  },
  {
    name: 'Mobile Hotel',
    type: 'MobileHybrid',
    url: 'https://play.google.com/store/apps/details?id=com.easyrez.hoteleskavia&hl=es_MX&gl=US&pli=1',
    github: '',
    image: KaviaSystem,
    slug: 'mobile-hotel',
    description:
      'This is a hotel mobile application when the customer is able to search and compare cost of rooms availables and see more information related to the hotel. The System made using Ionic and Angular.',
    tech: [
      'HTML',
      'Angular',
      'Sass',
      'XCODE',
      'Android Studio',
      'Google Play Console',
      'Maps SDK Google',
      'Geolocation',
      'App Store',
      'Postman',
      'Mobilscroll',
      'Trello',
      'Git',
    ],
  },
  {
    name: 'CarrerLab',
    type: 'Website',
    url: 'https://www.careerlab.me/',
    github: '',
    image: CarrerLabSystem,
    slug: 'carrerlab',
    description:
      'This is a services website made using Wordpress with page builder. Design provided in AdobeXD for a designer. ',
    tech: [
      'Wordpress',
      'HTML',
      'Javascript',
      'Css',
      'AdobeXD',
      'Javascript',
      'PHP',
      'MySQL',
      'ACF',
      'Custom Shortcode',
      'Divi Page Builder',
    ],
  },
  {
    name: 'Mostela',
    type: 'Website',
    url: 'https://www.mostela.com.mx/',
    github: '',
    image: MostelaSystem,
    slug: 'mostela',
    description:
      'This is a services website made using Wordpress with page builder. Design provided in Figma for a designer. ',
    tech: [
      'Wordpress',
      'HTML',
      'Javascript',
      'Css',
      'Figma',
      'Javascript',
      'PHP',
      'MySQL',
      'ACF',
      'Custom Shortcode',
      'Elementor Page Builder',
    ],
  },

  {
    name: 'Chocolates Imperial',
    type: 'Website',
    url: 'http://careerlab.me/',
    github: '',
    image: ChocolateSystem,
    slug: 'chocolates-imperial',
    description:
      'This is a product regional website made using Wordpress with a custom template, without page builder. ACF was used, also AdobeXD, HTML, CSS, Javascript, PHP, cPanel. Design provided in AdobeXD for a designer. ',
    tech: [
      'Wordpress',
      'HTML',
      'Javascript',
      'Css',
      'AdobeXD',
      'ACF',
      'PHP',
      'MySQL',
    ],
  },
  {
    name: 'Triadikas',
    type: 'Website',
    url: '',
    github: '',
    image: Freelance,
    slug: 'triadikas',
    description:
      'This is a services architect website made using Wordpress, without page builder. ACF was used, HTML, CSS, Javascript, PHP, AWS.',
    tech: [
      'Wordpress',
      'HTML',
      'Javascript',
      'Css',
      'ACF',
      'PHP',
      'MySQL',
      'Woocommerce',
      'WCFM Marketplace',
    ],
  },
  {
    name: 'Streming4u',
    type: 'Website',
    url: '',
    github: '',
    image: StreamingSystem,
    slug: 'streaming',
    description:
      'This is a services streaming website made using Wordpress, without page builder. ACF was used, also AdobeXD, HTML, CSS, Javascript, PHP, cPanel. Design provided in AdobeXD for a designer. ',
    tech: [
      'Wordpress',
      'HTML',
      'Javascript',
      'Css',
      'ACF',
      'PHP',
      'MySQL',
      'Woocommerce',
      'AdobeXD',
    ],
  },
  {
    name: 'Hacienda Santa Cruz',
    type: 'Website',
    url: ' ',
    github: '',
    image: HaciendaSystem,
    slug: 'hacienda-santa-cruz',
    description:
      'This is a hotel regional website made using Wordpress with a custom template, without page builder. ACF was used, also AdobeXD, HTML, CSS, Javascript, PHP, cPanel. Design provided in AdobeXD for a designer. ',
    tech: [
      'Wordpress',
      'HTML',
      'Javascript',
      'Css',
      'Sass',
      'AdobeXD',
      'ACF',
      'PHP',
      'MySQL',
      'Polylang',
    ],
  },
  {
    name: 'Confitería Brand & Media',
    type: 'Website',
    url: 'https://confiteriabm.com/',
    github: '',
    image: ConfiteriaSystem,
    slug: 'confiteria-bm',
    description:
      'This is a brand & media website made using Wordpress with a custom template, without page builder. ACF & Polylang were used, also AdobeXD, HTML, CSS, Javascript, PHP, cPanel. Design provided in AdobeXD for a designer. ',
    tech: [
      'Wordpress',
      'HTML',
      'Javascript',
      'Css',
      'AdobeXD',
      'ACF',
      'PHP',
      'MySQL',
    ],
  },
  {
    name: 'Ruta Iberoamericana',
    type: 'WebApp',
    url: '',
    github: '',
    image: RutaSystem,
    slug: 'ruta-iberoamericana',
    description:
      'This is a initiative website made using AngularJS with Laravel. Design provided in AdobeXD for a designer. ',
    tech: [
      'HTML',
      'Javascript',
      'AngularJS',
      'Css',
      'PHP',
      'Laravel',
      'cPanel',
    ],
  },
  {
    name: 'Vitela',
    type: 'WebApp',
    url: '',
    github: '',
    image: Freelance,
    slug: 'vitela',
    description:
      'This is a ecommerce books website made using VueJS with Laravel. Paypal and OxxoPay were implemented as payment method and API was developed with Lumen.',
    tech: [
      'HTML',
      'Javascript',
      'VueJS',
      'Webpack',
      'NPM',
      'Css',
      'Sass',
      'PHP',
      'Laravel',
      'SQL server',
      'Paypal',
      'Postman',
      'API Rest',
    ],
  },
  {
    name: 'Arsee',
    type: 'WebApp',
    url: '',
    github: '',
    image: Freelance,
    slug: 'arsee',
    description:
      'This is a private application made using Angular. Desing provided by designer in Figma.',
    tech: [
      'HTML',
      'Javascript',
      'Angular',
      'Angular Boostrap',
      'Tyscript',
      'NPM',
      'Css',
      'Sass',
      'Jira',
      'Kanban',
      'Git',
      'GitHub Actions',
      'Discord',
    ],
  },
  {
    name: 'Finvivir Backoffice',
    type: 'WebApp',
    url: '',
    github: '',
    image: FinvivirAdminSystem,
    slug: 'finvivir-backoffice',
    description:
      'This is a job board application when recruiters are able to manage all request from posibles candidates and decide the next step, made using Angular. Desing provided by designer in Figma.',
    tech: [
      'HTML',
      'Javascript',
      'Angular',
      'Angular Boostrap',
      'Tyscript',
      'NPM',
      'Css',
      'Sass',
      'Jira',
      'Kanban',
      'Git',
      'GitHub Actions',
      'Discord',
    ],
  },
  {
    name: 'Finvivir Website',
    type: 'WebSite',
    url: '',
    github: '',
    image: FinvivirSystem,
    slug: 'finvivir-web',
    description:
      'This is a customer application when candidates are able to search open jobs and request your information, made using Angular. Desing provided by designer in Figma.',
    tech: [
      'HTML',
      'Javascript',
      'Angular',
      'Angular Boostrap',
      'Tyscript',
      'NPM',
      'Css',
      'Sass',
      'Jira',
      'Kanban',
      'Git',
      'GitHub Actions',
      'Discord',
    ],
  },
  {
    name: 'DemandPlanner',
    type: 'WebApp',
    url: '',
    github: '',
    image: Freelance,
    slug: 'demand-planer',
    description:
      'This is a gas station application when administrator are able to see statistics and report related to sell gas and they are able to see all invoices generated in each gas station, made using Angular. PrimeNG was used for desing.',
    tech: [
      'HTML',
      'Javascript',
      'Angular',
      'PrimeNG',
      'ngx-permission',
      'Tyscript',
      'NPM',
      'Css',
      'Sass',
      'Jira',
      'Lumen API',
      'Postman',
      'SQL server',
      'Kanban',
      'Git',
      'GitHub Actions',
      'Discord',
    ],
  },
  {
    name: 'Start Fun',
    type: 'WebApp',
    url: '',
    github: '',
    image: StartFunSystem,
    slug: 'start-fun',
    description:
      'This is a tour application when administrator are able to create tour, amenities, package, ticket and more, made using Angular.',
    tech: [
      'HTML',
      'Javascript',
      'Angular',
      'Angular Boostrap',
      'ngx-permission',
      'Tyscript',
      'NPM',
      'Css',
      'Sass',
      'Lumen API',
      'Postman',
      'MySQL',
      'Jira',
      'Kanban',
      'Firebase',
      'Git',
      'GitHub Actions',
      'Discord',
    ],
  },
  {
    name: 'ReOrder Printer',
    type: 'WebApp',
    url: '',
    github: '',
    image: Freelance,
    slug: 're-order',
    description:
      'This is a printer application when administrator are able to create previous order of his customer and he can manage all order status, made using Angular.',
    tech: [
      'HTML',
      'Javascript',
      'Angular',
      'Angular Boostrap',
      'ngx-permission',
      'Tyscript',
      'NPM',
      'Css',
      'Sass',
      'Lumen API',
      'Postman',
      'MySQL',
      'Trello',
      'Kanban',
      'Firebase',
      'Git',
      'GitHub Actions',
      'Discord',
    ],
  },
  {
    name: 'CheckList',
    type: 'WebApp',
    url: '',
    github: '',
    image: Freelance,
    slug: 'checklist',
    description:
      'This is a check list application when user are able to manage different list and categories and mark when one activity has done and even it was possible print screen and upload in specific task, made using Angular.',
    tech: [
      'HTML',
      'Javascript',
      'Angular',
      'Angular Boostrap',
      'Tyscript',
      'NPM',
      'Css',
      'Sass',
      'Lumen API',
      'Postman',
      'MySQL',
      'Trello',
      'Kanban',
      'Firebase',
      'Git',
      'GitHub Actions',
      'Upwork',
    ],
  },
  {
    name: 'BikeTours',
    type: 'WebApp',
    url: '',
    github: '',
    image: BikerTourSystem,
    slug: 'biketours',
    description:
      'This is a tour application focused on bikers when biker is able to see the different tour available and reserve one of them, made using Angular. Desing provided by designer in Figma.',
    tech: [
      'HTML',
      'Javascript',
      'Angular',
      'Angular Boostrap',
      'Tyscript',
      'NPM',
      'Css',
      'Sass',
      'Lumen API',
      'Postman',
      'MySQL',
      'Jira',
      'Kanban',
      'Git',
      'GitHub Actions',
    ],
  },
  {
    name: 'Staff',
    type: 'WebApp',
    url: '',
    github: '',
    image: Freelance,
    slug: 'netcorp',
    description:
      'I had the opportunity to work as Staff for a few months. My activities that I did were create and modify new components and implement new services of API. It made using ReactJS and desing provided by the designer',
    tech: [
      'HTML',
      'Javascript',
      'ReactJS',
      'HOC',
      'AdobeXD',
      'NPM',
      'Css',
      'Sass',
      'Jira',
      'Kanban',
      'Git',
      'Bitbucket',
      'Telegram',
    ],
  },
  /* {
    name: 'LifeInsureEase',
    type: 'Website',
    url: 'https://lifeinsureease.in/',
    github: 'https://github.com/DevRohit06/insurance-website',
    image: LifeInsureEase,
    slug: 'lifeinsureease',
    description:
      'This is an Insurance website made using Astro, Reactjs and Tailwind css. ',
    tech: ['HTML', 'Javascript', 'Css', 'Tailwind css', 'Astro', 'Reactjs'],
  },
  {
    name: 'Portfolio Website',
    type: 'Website',
    url: 'https://rohitk06.site/',
    github: 'https://github.com/DevRohit06/Portfolio-website',
    image: Portfolio,
    slug: 'portfolio',
    description:
      'This is my Portfolio website made using Astro, Reactjs and Tailwind css. ',
    tech: ['HTML', 'Javascript', 'Css', 'Tailwind css', 'Astro', 'Reactjs'],
  },
  {
    name: 'DocAid',
    type: 'Website',
    url: 'https://doc-aid.vercel.app/',
    github: 'https://github.com/DevRohit06/DocAid',
    image: docAid,
    slug: 'docaid',
    description: 'Website template for Health related businesses',
    tech: ['HTML', 'Javascript', 'CSS', 'Tailwind css', 'ReactJS'],
  },
  {
    name: 'DevBlogs',
    type: 'WebApp',
    url: 'https://www.devblogs.xyz/',
    github: 'https://github.com/DevRohit06/blog',
    image: blog,
    slug: 'devblogs',
    description: 'This is a Blogging website made for technology lovers.',
    tech: ['HTML', 'Javascript', 'Css', 'Tailwind css', 'Astro', 'Markdown'],
  },
  {
    name: 'Ras Production',
    type: 'Website',
    url: 'https://rasproduction.vercel.app/',
    github: 'https://github.com/DevRohit06/videography-website',
    image: ras,
    slug: 'ras',
    description:
      'This is an Portfolio website for videography businesses made using HTML, Javascript, Css and Tailwind css it practices modern ui with dark theme ',
    tech: ['HTML', 'Javascript', 'Css', 'Tailwind css'],
  },
  {
    name: 'Joke Generator',
    type: 'WebApp',
    url: 'https://jokes-generator-with-api.vercel.app/',
    github: 'https://github.com/DevRohit06/Jokes-Generator-With-API',
    image: joke,
    slug: 'joke',
    description:
      'The website which generates joke with multi topics such as anime, programming, etc.',
    tech: ['React', 'Javascript', 'Css', 'Tailwind css', 'express', 'nodejs'],
  },

  {
    name: 'Lofi Beats',
    type: 'Website',
    url: 'https://lofibeats-3oo4q8gbg-lofi.vercel.app/',
    github: 'https://github.com/Lofi-Beats/lofibeats',
    image: lofi,
    slug: 'lofibeats',
    description:
      'Website that was built for Discord music bot named lofi beats built using plain html javascript and tailwind css',
    tech: ['HTML', 'Javascript', 'Css', 'Tailwind css'],
  }, */
];

export function getData() {
  return data;
}
